# Generated by Django 4.0.5 on 2022-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('featured_image', models.FileField(upload_to='products')),
                ('description', models.TextField()),
                ('sale_price', models.FloatField()),
                ('price', models.FloatField()),
                ('isFeatured', models.BooleanField()),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
    ]
