# Generated by Django 4.0.5 on 2022-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('publish_date', models.DateField(auto_now=True)),
                ('featured_image', models.FileField(upload_to='blogs')),
            ],
        ),
    ]
